[package]
name = "hoplight"
version = "0.1.0"
authors = ["Peter Reid <peter.d.reid@gmail.com>"]

[dependencies]
byteorder = "*"
checked_int_cast = "1.0.0"
arrayref = "0.3.2"
rand = "0.3"

[dependencies.rust-crypto]
git = "https://github.com/PeterReid/rust-crypto.git"
